version: '3.7'

services:

  db:
    image: postgres:12.4-alpine
    env_file:
      - ../confs/enabled/db.env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"

  avaportal:
    image: 'ifrn/suap_ead_base:1.5.14'
    ports:
      - "80:8000"
    env_file:
      - ../confs/enabled/db.env
      - ../confs/enabled/avaportal.env
    volumes:
      - '../src:/apps/app'
      - "../volumes/media:/var/media"
      - "../volumes/static:/var/static"
