version: '3.7'

services:

  proxy:
    image: nginx:1.19.2-alpine
    restart: always
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../confs/enabled/proxy:/etc/nginx/conf.d"
      - "../volumes/static:/var/static"
      - "../volumes/media:/var/media"

  db:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - ../confs/enabled/db.env
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"

  avaportal:
    image: 'ifrn/avaportal:1.0.7'
    restart: always
    ports:
      - "7001:8000"
    env_file:
      - ../confs/enabled/db.env
      - ../confs/enabled/avaportal.env
    volumes:
      - '/Users/kelson/devel/ifrn/suap-ead/lib_suap_ead:/apps/lib_suap_ead'
      - '../src:/apps/app'
      - "../volumes/media:/var/media"
      - "../volumes/static:/var/static"
