version: '3.7'

services:

  cache:
    image: redis:7.0.2-alpine
    restart: always
    env_file:
      - ./confs/enabled/cache.env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  fakedb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/fakedb.env
    volumes:
      - "./volumes/fakedb_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  fakeapp:
    image: 'ifrn/suapfake:1.0.12'
    build: src/python/fake
    restart: always
    ports:
      - '8001:8000'
    env_file:
      - ./confs/enabled/fakedb.env
      - ./confs/enabled/fakeapp.env
      - ./confs/enabled/cache.env
    volumes:
      - './src/python/fake:/apps/app'
      - './volumes/fakeapp_media:/var/media'
      - './volumes/fakeapp_static:/var/static'
    depends_on:
      - fakedb
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://fakeapp:8000/health/ | grep 'Database: OK' || exit 1"]
      interval: 3s
      timeout: 1s
      start_period: 1s
      retries: 30

  portaldb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/portaldb.env
    volumes:
      - "./volumes/portaldb_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  portalapp:
    image: 'ifrn/avaportal:1.0.12'
    build: src/python/portal
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./confs/enabled/portaldb.env
      - ./confs/enabled/portalapp.env
      - ./confs/enabled/cache.env
    volumes:
      - './src/python/portal:/apps/app'
      - './volumes/portalapp_media:/var/media'
      - './volumes/portalapp_static:/var/static'
    depends_on:
      - portaldb
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://portalapp:8000/health/ | grep 'Database: OK' || exit 1"]
      interval: 3s
      timeout: 1s
      start_period: 1s
      retries: 30

  avazldb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/avazldb.env
    volumes:
      - "./volumes/avazl_pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  avazlapp:
    image: 'ctezlifrn/moodle:4.0.3-php8.0-001'
    restart: always
    ports:
      - '8011:80'
    env_file:
      - ./confs/enabled/avazldb.env
      - ./confs/enabled/avazlapp.env
    volumes:
      # Plugins
      # - './src/php/moodle-customfield_file:/var/www/html/customfield/field/file'
      - './src/php/moodle__auth_suap:/var/www/html/auth/suap'

      # Data
      - './volumes/avazl_moodledata:/var/moodledata'
    depends_on:
      - avazldb
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://avazlapp:80/ | grep AVA_do_Zona_Leste || exit 1"]
      interval: 3s
      timeout: 1s
      start_period: 1s
      retries: 30

  avapresencialdb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/avapresencialdb.env
    volumes:
      - "./volumes/avapresencial_pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  avapresencialapp:
    image: 'ctezlifrn/moodle:4.0.3-php8.0-001'
    restart: always
    ports:
      - '8021:80'
    env_file:
      - ./confs/enabled/avapresencialdb.env
      - ./confs/enabled/avapresencialapp.env
    volumes:
      # Plugins
      # - './src/php/moodle-customfield_file:/var/www/html/customfield/field/file'

      # Data
      - './volumes/avapresencial_moodledata:/var/moodledata'
    depends_on:
      - avazldb
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://avapresencialapp:80/ | grep AVA_do_Presencial || exit 1"]
      interval: 3s
      timeout: 1s
      start_period: 1s
      retries: 30
