version: '3.7'

services:

  # proxy:
  #   image: nginx:1.21.6-alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:  
  #     - "./confs/enabled/proxy/default.conf:/etc/nginx/conf.d/default.conf"
  #     - "../volumes/app_static:/var/app_static"
  #     - "../volumes/app_media:/var/app_media"
  #   healthcheck:
  #     test: ["CMD", "curl", "--fail", "http://localhost"]
  #     interval: 3s
  #     timeout: 3s
  #     retries: 3
  #     start_period: 10s

  cache2:
    image: redis:7.0.2-alpine
    restart: always
    env_file:
      - ./confs/enabled/cache.env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  fakedb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/fakedb.env
    volumes:
      - "./volumes/fakedb_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  fakeapp:
    image: 'ifrn/suapfake:1.0.12'
    build: src/python/fake
    restart: always
    ports:
      - '8001:8000'
    env_file:
      - ./confs/enabled/fakedb.env
      - ./confs/enabled/fakeapp.env
      - ./confs/enabled/cache.env
    volumes:
      - './src/python/fake:/apps/app'
      - './volumes/fakeapp_media:/var/media'
      - './volumes/fakeapp_static:/var/static'
    depends_on:
      - fakedb

  portaldb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/portaldb.env
    volumes:
      - "./volumes/portaldb_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  portalapp:
    image: 'ifrn/avaportal:1.0.12'
    build: src/python/portal
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./confs/enabled/portaldb.env
      - ./confs/enabled/portalapp.env
      - ./confs/enabled/cache.env
    volumes:
      - './src/python/portal:/apps/app'
      - './volumes/portalapp_media:/var/media'
      - './volumes/portalapp_static:/var/static'
    depends_on:
      - portaldb

  avazldb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/avazldb.env
    volumes:
      - "./volumes/avazl_pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  avazlapp:
    # image: moodlehq/moodle-php-apache:8.1-bullseye # not for production
    # image: moodlehq/moodle-php-apache:7.4-bullseye
    image: 'ifrn/mooodle:3.11.7'
    build: src/php
    restart: always
    ports:
      - '8011:80'
    env_file:
      - ./confs/enabled/avazldb.env
      - ./confs/enabled/avazlapp.env
    volumes:
      # Plugins
      # - './src/php/moodle-customfield_file:/var/www/html/customfield/field/file'
      - './src/php/moodle__auth_suap:/var/www/html/auth/suap'

      # Data
      - './volumes/avazl_moodledata:/var/moodledata'
    depends_on:
      - avazldb

  avapresencialdb:
    image: postgres:14.3-alpine
    restart: always
    env_file:
      - ./confs/enabled/avapresencialdb.env
    volumes:
      - "./volumes/avapresencial_pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ava_user"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  avapresencialapp:
    # image: moodlehq/moodle-php-apache:8.1-bullseye # not for production
    # image: moodlehq/moodle-php-apache:7.4-bullseye
    image: 'ifrn/mooodle:3.11.7'
    build: src/php
    restart: always
    ports:
      - '8021:80'
    env_file:
      - ./confs/enabled/avapresencialdb.env
      - ./confs/enabled/avapresencialapp.env
    volumes:
      # Plugins
      # - './src/php/moodle-customfield_file:/var/www/html/customfield/field/file'

      # Data
      - './volumes/avapresencial_moodledata:/var/moodledata'
    depends_on:
      - avazldb
