version: '3.7'

services:

  proxy:
    image: nginx:1.21.6-alpine
    restart: always
    ports:
      - "80:80"
    volumes:  
      - "./confs/enabled/proxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "../volumes/app_static:/var/app_static"
      - "../volumes/app_media:/var/app_media"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - ./confs/enabled/db.env
    volumes:
      - "./volumes/db_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  cache:
    image: redis:7.0.0
    restart: always
    env_file:
      - ./confs/enabled/cache.env
    volumes:
      - "./volumes/cache_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 10s

  app:
    image: 'ifrn/avaportal:1.0.12'
    build: .
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./confs/enabled/db.env
      - ./confs/enabled/app.env
      - ./confs/enabled/cache.env
    volumes:
      - './src/python:/apps/app'
      - './volumes/app_media:/var/media'
      - './volumes/app_static:/var/static'
    depends_on:
      db:
        condition: service_started

  # fake:
  #   image: 'ifrn/avaportal:1.0.12'
  #   build: .
  #   restart: always
  #   ports:
  #     - '8000:8000'
  #   env_file:
  #     - ./confs/enabled/db.env
  #     - ./confs/enabled/cache.env
  #     - ./confs/enabled/fake.env
  #   volumes:
  #     - './src/python:/apps/app'
  #     - './volumes/fake_media:/var/media'
  #     - './volumes/app_static:/var/static'
  #   depends_on:
  #     db:
  #       condition: service_started

  # zl01:
  #   # image: moodlehq/moodle-php-apache:8.1-bullseye # not for production
  #   image: moodlehq/moodle-php-apache:7.4-bullseye
  #   restart: always
  #   ports:
  #     - '8001:80'
  #   env_file:
  #     - ./confs/enabled/db.env
  #     - ./confs/enabled/cache.env
  #   volumes:
  #     # Sources
  #     - './src/php/moodle311:/var/www/html/zl'

  #     # Settings
  #     - './src/php/moodle-config/config.php:/var/www/html/zl/config.php'

  #     # Plugins
  #     - './src/php/moodle-customfield_file:/var/www/html/zl/customfield/field/file'

  #     # Data
  #     - './volumes/moodledata_zl:/var/moodledata'
  #   depends_on:
  #     db:
  #       condition: service_started
